<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>TSKHook-melon</AssemblyName>
    <Description>melonloader implementation of TSKHook</Description>
    <Version>1.1.6</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RootNamespace>TSKHook</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <PropertyGroup>
    <GamePath>C:\Users\husky\Twinkle_StarKnightsX</GamePath>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
	
  <ItemGroup>
    <GameDlls Include="
              $(GamePath)\MelonLoader\net6\*.dll;
              $(GamePath)\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll;
              $(GamePath)\MelonLoader\Il2CppAssemblies\Il2Cpp*.dll;
              $(GamePath)\MelonLoader\Il2CppAssemblies\Unity*.dll;
              $(GamePath)\MelonLoader\Il2CppAssemblies\spine*.dll;">
    </GameDlls>
    <Reference Include="@(GameDlls)">
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy config.json $(OutDir);
                   copy SS_Notification.ps1 $(OutDir)" />
  </Target>
	
</Project>
